// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkXLtOtNvIjiGp3iVR2-8wPNNqHw7cGwE',
    appId: '1:695992104136:android:7e8282ec4d90aea338e1fd',
    messagingSenderId: '695992104136',
    projectId: 'flutterappdemo-f4a02',
    storageBucket: 'flutterappdemo-f4a02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9hgQAO0sujbt18RT5BV7OBnnWwPt9Q50',
    appId: '1:695992104136:ios:d8023bc1e0f84c5438e1fd',
    messagingSenderId: '695992104136',
    projectId: 'flutterappdemo-f4a02',
    storageBucket: 'flutterappdemo-f4a02.appspot.com',
    iosBundleId: 'com.example.fibonacci',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9hgQAO0sujbt18RT5BV7OBnnWwPt9Q50',
    appId: '1:695992104136:ios:b40ecff0fc61e07338e1fd',
    messagingSenderId: '695992104136',
    projectId: 'flutterappdemo-f4a02',
    storageBucket: 'flutterappdemo-f4a02.appspot.com',
    iosBundleId: 'com.example.fibonacci.RunnerTests',
  );
}
